FROM python:3

ENV PYTHONUNBUFFERED 0

RUN apt-get update && apt-get -y install python3-dev default-libmysqlclient-dev

RUN mkdir /app
WORKDIR /app

ADD    requirements.txt    /app/

#Install dependencies
RUN    pip install --upgrade pip
RUN    pip install -r requirements.txt

ADD . /app/